#!/usr/bin/python
#  cas
#  cas cmd line interface
#  Copyright (C) 2010 Adam Stokes
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#   
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#   
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

""" cas - core accessibility system.
"""
from caslib.cas import CasApplication
import os
import sys

if __name__=="__main__":
    # Begin CAS
    app = CasApplication(sys.argv[1:])
    sys.exit(app.run())
