#!/usr/bin/perl

=head1 NAME

makerpm

=head1 DESCRIPTION

attempts to build rpm before a git commit

=cut

use strict;
use warnings;
use feature qw ( say );

# Run make rpm
say "Running build";
my $exitcode = system("make build");
if ($exitcode > 0) {
    exit 128;
} else {
    exit 0;
}
