.TH "CAS-ADMIN" "1" "CAS-ADMIN" "cas administration interface"

.SH NAME
cas-admin \- Administrator tools for building rpm/server database.

.SH DESCRIPTION
.TP
\fIcas-admin\fP is a tool used to build necessary data for use with cas.
.SH OPTIONS
.TP
.BI \--server
Populate server database for automatic processing of core files.
.TP
.B \-p
Purge data based on set days (see purge options)
.SH PURGE OPTIONS
.TP
.B \-d [days]
Define how many days back you wish to purge data, default is 90 days.

.SH SEE ALSO
.sp
cas-server(1)
.in
cas(1)
.SH AUTHOR
.sp
Written by Adam Stokes
.SH "REPORTING BUGS"
.sp
Report bugs to <astokes@redhat.com> or https://fedorahosted.org/cas/report
.SH COPYRIGHT
.sp
Copyright \(co 2007-2010  Adam Stokes
.in

This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
