.TH "cas.conf" "5" "CAS" "cas configuration file"
.SH NAME
cas.conf \- Cas configuration file.
.SH DESCRIPTION
.sp
cas.conf is the configuration file for cas.
.SH [settings] OPTIONS
.sp
.in
.B casuser: 
(Required) User to run cas, recommended to run as someone other than root.

.in
.B sshkey:
(Required) Used for ssh negotiation, these are generated with ssh-keygen.

.in
.B kernels:
(Required) Describes the location of where kernel-debuginfo packages are to be stored. This can range anywhere from an nfs mount, samba share, local disk or any other type of media the cas server can access.

.in
.B regexExcludeDir:
Directories that may be within the search path that doesn’t need to be included. This is a shell format so globs like */*/data are accepted.

.in
.B regexExcludeFile:
Any files that need to be excluded from the search path. This is also a shell format */*/badfile.txt.

.in
.B regexType:
(Required) Defines the regex syntax to use within find. Doing a man find and searching for regextype will give you the allowable syntaxess.

.in
.B rpmFilters:
(Required) This is a emacs based regular expression which is essentially passed to a find command to locate the various kernel-debuginfo packages defined in kernels directive.

.in
.B debugLevel:
As the name suggest it will set the debug level for CAS output. Currently the only accepted values are DEBUG|INFO.

.in
.B workDirectory:
(Required) Defines where all processed cores will be placed. This mount point will need to have the most storage assigned to it. Depending on how many cores are processed in a given timeframe this area will fill up quickly.

.in
.B smtphost:
If wanting output of CAS processing email to a certain address this directive needs to be set. Note that the mail server should not require smtp authentication.

.in
.B database:
(Required) Define where the sqlite database will reside. Note the casuser will need to have read/write access to this database.

.SH [maintenance] OPTIONS
.sp
.in
.B purgeLimit:
Define amount of day(s) back wish to keep physical data on system.

.in
.B autoPurge:
Yes/No setting if wanting cas-admin to auto purge stale data on each run.

.SH [advanced] OPTIONS
.sp
.in
.B crash_32:
Primarily used on x86_64 systems to process x86 cores. If x86 version of crash is installed this directive can be set to the crash binary and CAS will automatically process x86 cores on a x86_64 machine. Note this is only available if the CAS server is a x86_64 machine.

.in
.B buffersize:
Extend the read buffer when analyzing a core for a timestamp. Note this is normally needed for itanium cores, otherwise, the default is fine.

.SH FILES
.sp
/etc/cas.conf
.SH "SEE ALSO"
.sp
cas(1)
.in
cas-admin(1)
.in
Full documentation located in /usr/share/doc/cas-<version>.
