.TH "CAS" "1" "CAS" "cas command line interface"

.SH NAME
cas \- Tool to configure core analysis environment.

.SH DESCRIPTION
.sp
.B cas
is a tool used to automatically configure an environment for viewing coredumps.
.SH OPTIONS
.sp
.TP
.B \-i identifier
Specify an id to associate with current cas job, normally a support ticket of
some sort.
.TP
.B \-f [file]
Define a core file to be processed.
.TP
.B \-e [email]
Provide an email address for result notification
.TP
.B \-m
Extract current loaded modules from debug kernels.
.TP
.B \--compress [file]
Compress file using system supplied compression utilties.
.TP
.B \--strip [file]
Strips vmcore of unecessary pages. (Not active for now)
.TP
.B \--job [job-id]
Define job to associate to this analysis (Normally this is handled by the
web interface)

.SH "SEE ALSO"
.sp
cas-admin(1)
.in
cas-server(1)
.in
cas.conf(5)
.SH AUTHOR
.sp
Written by Adam Stokes
.SH "REPORTING BUGS"
.sp
Report bugs to <astokes@redhat.com> or https://fedorahosted.org/cas/report
.SH COPYRIGHT
.sp
Copyright \(co 2007-2010  Adam Stokes
.in

This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
