#!/bin/sh                                                                                                                    
# -*- mode: sh; -*-                                                                                                                           
# cas-server          Start/Stop the cas-server.                                                                           
#                                                                                                                            
# chkconfig: 2345 90 60                                                                                                      
# description: cas-server is the web frontend to CAS ( core analysis system )
                                                                                                                             
### BEGIN INIT INFO                                                                                                          
# Provides: cas-server
# Required-Start: $local_fs $syslog                                                                                          
# Required-Stop: $local_fs $syslog                                                                                           
# Default-Start:  2345                                                                                                       
# Default-Stop: 90                                                                                                           
# Short-Description: run cas-server
# Description: cas-server is the web frontend to CAS ( core analysis system )
### END INIT INFO  

RETVAL=0
prog="cas-server"

# function library
. /etc/rc.d/init.d/functions

start () {}
stop() {}
restart() {}
status() {}


case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    status)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|}"
        exit 2
esac
exit $?
